import { test, expect } from '@playwright/test';
import { datos } from '../../data/produccion';
test('test', async ({ page }) => {
  await page.goto(datos.url);
  await page.getByRole('textbox', { name: 'Usuario' }).click();
  await page.getByRole('textbox', { name: 'Usuario' }).fill(datos.login.usuario);
  await page.getByRole('textbox', { name: 'Contraseña' }).click();
  await page.getByRole('textbox', { name: 'Contraseña' }).fill(datos.login.password);
  await page.getByRole('button', { name: 'INGRESAR AL SISTEMA' }).click();
  await page.getByRole('link', { name: 'Leads' }).click();
  await page.getByRole('button', { name: 'Editar' }).first().click();
  await page.getByRole('textbox', { name: 'Teléfono' }).click();
  await page.getByRole('textbox', { name: 'Teléfono' }).fill('3165627982');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('murillowal2026');
  await page.getByRole('textbox', { name: 'Email' }).press('Alt+6');
  await page.getByRole('textbox', { name: 'Email' }).press('Alt+4');
  await page.getByRole('textbox', { name: 'Email' }).fill('murillowal2026@gmail.com');
  await page.getByRole('combobox').first().selectOption('Contactado');
  await page.getByRole('button', { name: 'Guardar cambios' }).click();
  await page.getByText('Lead actualizado correctamente').click();
});