import { test, expect } from '@playwright/test';
import { datos } from '../../data/produccion';
test('test', async ({ page }) => {
  await page.goto(datos.url);
  await page.getByRole('textbox', { name: 'Usuario' }).click();
  await page.getByRole('textbox', { name: 'Usuario' }).fill(datos.login.usuario);
  await page.getByRole('textbox', { name: 'Contraseña' }).click();
  await page.getByRole('textbox', { name: 'Contraseña' }).fill(datos.login.password);
  await page.getByRole('button', { name: 'INGRESAR AL SISTEMA' }).click();
  await page.getByRole('link', { name: 'Leads' }).click();
  await page.getByRole('textbox', { name: 'Nombre completo' }).click();
  await page.getByRole('textbox', { name: 'Nombre completo' }).fill('walter murillo');
  await page.getByRole('textbox', { name: 'Teléfono' }).click();
  await page.getByRole('textbox', { name: 'Teléfono' }).fill('3103262999');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('waltermu2026');
  await page.getByRole('textbox', { name: 'Email' }).press('Alt+6');
  await page.getByRole('textbox', { name: 'Email' }).press('Alt+4');
  await page.getByRole('textbox', { name: 'Email' }).fill('waltermu2026@gmail.com');
  await page.getByRole('button', { name: 'Crear lead' }).click();
  await page.getByText('Lead creado correctamente').click();
});