import { test, expect } from '@playwright/test';
import { datos } from '../../data/config';
test('test', async ({ page }) => {
  await page.goto(datos.url);
  await page.getByRole('textbox', { name: 'Usuario' }).click();
  await page.getByRole('textbox', { name: 'Usuario' }).fill(datos.login.usuario);
  await page.getByRole('textbox', { name: 'Contraseña' }).click();
  await page.getByRole('textbox', { name: 'Contraseña' }).fill(datos.login.password);
  await page.getByRole('button', { name: 'INGRESAR AL SISTEMA' }).click();
  await page.getByRole('link', { name: 'Leads' }).click();
  await page.getByRole('heading', { name: '👤 fghfgh' }).click();
  await page.locator('div:nth-child(5) > .space-y-3 > .flex > .px-5.py-2.rounded.font-bold.transition.bg-blue-600').click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('mmmiguelmurillo20@gmail.com');
  await page.getByRole('combobox').first().selectOption('Contactado');
  await page.getByRole('button', { name: 'Guardar cambios' }).click();
  await page.getByText('Lead actualizado correctamente').click();
  await expect(page.getByText('Lead actualizado correctamente')).toBeVisible();
  await page.close();
});